# Workflow for checking that source code is formatted by clang-format.
name: clang-format check

on: [ push, pull_request ]

jobs:
  build:
    name: Check by clang-format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Show clang-format version
      run: >
        clang-format --version
    - name: Perform checking by clang-format
      run: >
        find . -iname '*.c' -o -iname '*.cc' -o -iname '*.cpp' -o -iname '*.h'
        | xargs clang-format --dry-run --Werror
